version: '3.8'

services:
  webrisetest:
    ports:
      - "8080:8080"
    build: .
    container_name: webrisetest
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/webrisetest_database
      SPRING_DATASOURCE_USERNAME: webrisetest_user
      SPRING_DATASOURCE_PASSWORD: webrisetest_password

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: webrisetest_database
      POSTGRES_USER: webrisetest_user
      POSTGRES_PASSWORD: webrisetest_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: